#ifndef _CONFIG_HPP_
#define _CONFIG_HPP_

#define MILLISECOND_PRECISION false

#define INTERNAL_LED_BLINK_INTERVAL 200
#define CHANNEL_SWITCH_INTERVAL 200
#define FILE_SAVE_INTERVAL 10000
#define RTS_COMMAND_SWITCHING_INTERVAL 16000

#define SD_CS_PIN D8
#define SQW_INTERRUPT_PIN D3
#define ESP8266_ONBOARD_LED D4

#define WIFI_SSID "Igor"
#define WIFI_PASSWD ""

#endif